config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pins#index'

  get "/sessions/new" => "sessions#new", as: :sign_in
  post "/sign-in" => "sessions#create", as: :auth
  delete "/sign-out" => "sessions#destroy", as: :sign_out

  resources :pins
  resources :users

end

app/models/pin.rb
class Pin < ActiveRecord::Base
   belongs_to :user
   mount_uploader :photo, PhotoUploader

   validates :link, presence: true
   validates :title, presence: true
   validates :photo, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :pins
   has_secure_password

   validates :username, presence: true
   validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_action :fetch_current_user

  def fetch_current_user
  @current_user = User.find_by id: session[:user_id]
  end

  def authenticate_user!
    if signed_in?
    @current_user = User.find session[:user_id]
   else
    redirect_to sign_in_path
   end
end

def signed_in?
  session[:user_id].to_i > 0
end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

   before_action :authenticate_user!

   def index
      @pin = Pin.new
      @pins = Pin.all
   end

   def new
      @pin = Pin.new
   end

   def create
     @pin = Pin.new params.require(:pin).permit(:title, :link, :photo, :notes)
     @pin.user_id = session[:user_id]

     respond_to do |format|
       if @pin.save
         @pins = Pin.all
         @pin = Pin.new
         format.html { redirect_to @pin }
         format.js   { }
       else
         format.html { render :new }
         format.js { }
       end
     end
   end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   def new
      if @current_user
         redirect_to root_path
      end
   end


   def create
    username = params[:username]
    password = params[:password]

    user = User.find_by username: username
    if user.try(:authenticate, password)
      session[:user_id] = user.id
      @current_user = user
    end

    # handle both HTML requests and js requests
    respond_to do |format|
      format.html do
        if @current_user
          redirect_to root_path
        else
          render :new
        end
      end
      format.js { }
    end

  end


     def destroy
      session[:user_id] = nil
      redirect_to root_path
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
   @user = User.new
end

def create
@user = User.new(params.require(:user).permit(:username, :password))
   if @user.save
     @current_user = @user
      session[:user_id] = @user.id
      redirect_to root_path
   else
     render :new
   end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_user_widget.html.erb
            <% if @current_user == nil %>
            <ul class="nav navbar-nav navbar-left">
             <li><a>Welcome, <b>Guest</b></a></li>
          </ul>
               <% else %>

               <ul class="nav navbar-nav navbar-left">
                <li><a>Welcome, <b><%=@current_user.username%></b></a></li>
             </ul>

             <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Logout", sign_out_path, method: :delete %></li>
            </ul>
         <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinquisite</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag :defaults %>

  <%= csrf_meta_tags %>
</head>
<body>
   <div class='container-fluid'>
      <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
             <div id="navbar" class="navbar-collapse collapse">
                <div id="header-nav">
      <%= render partial: "layouts/user_widget" %>
   </div>
   </div><!--/.nav-collapse -->
</div>
</nav>
</div>
<br><br><br>


<div class='container-fluid'>
   <div id="pinslist">
<%= yield %>
</div>
</div>
</body>
</html>

app/views/pins/_add_form.html.erb
<div class="modal fade" id="add-pin-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div id="pin-form">
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for @pin|| Pin.new, remote: true, multipart: true do |f| %>

  <%= f.input :title %>
  <%= f.input :link %>
  <%= f.input :photo %>
  <%= f.input :notes %>
  <%= f.submit class: "btn btn-success btn-block" %>

<% end %>

app/views/pins/_pin_list.html.erb
<% @current_user.pins.each do |p| %>
<div class="col-md-3">
   <div class="vertical-smallborder">
      <section>
         <%= link_to image_tag(p.photo.thumb) %>
         <div class="text">
            <span class="txt-black">
               <h1><%= p.title %></h1>
               <p><%= p.notes %></p>
               <a class="button" href="<%= p.link %>">Go to page</a>
            </span>
         </div>
      </section>
   </div>
    </div>
<% end %>

<div class="col-md-3">
<a class="entire" data-toggle="modal" data-target="#add-pin-modal">
<div class="vertical-smallborder">
<section>
<i class="fa fa-plus-circle fa-4x"></i>
<p>Add Pin</p>
</section>
</div>
</a>
</div>

<div class="modal fade" id="add-pin-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div id="pin-form">
        <%= render partial: 'pins/form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/create.js.erb
<% if @pin.errors.any? %>
  $("#pin-form").html("<%= escape_javascript render partial: 'form' %>");
  <% else %>
    $("#pin-form").html("<%= j render partial: 'form' %>");
    $("#pin-table").html("<%= j render partial: 'pin_list' %>");
  <% end %>

app/views/pins/index.html.erb
<div id ="pin-table">
   <%= render partial: 'pin_list' %>
</div>

<br>

app/views/pins/new.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<div class="panel panel-default col-md-4 col-md-offset-4">
   <h1 class='heading text-center'>Sign Up</h1>
   <div class="panel-body">
<%= simple_form_for(@user) do |f| %>
  <%= f.input :username %>
  <%= f.input :password %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>
</div>
</div>